export const LIST_CATEGORY = 'LIST_CATEGORY';
export const GET_CATEGORY_DETAIL = 'GET_CATEGORY_DETAIL';
export const GET_CATEGORY_DETAIL_HOT = 'GET_CATEGORY_DETAIL_HOT';
export const GET_CATEGORY_DETAIL_FOLLOWED = 'GET_CATEGORY_DETAIL_FOLLOWED';
export const GET_CATEGORY_DETAIL_FAVORITED = 'GET_CATEGORY_DETAIL_FAVORITED';
export const GET_CATEGORY_DETAIL_NEW = 'GET_CATEGORY_DETAIL_NEW';
export const GET_MEDIA_DETAIL = 'GET_MEDIA_DETAIL';
export const SEARCH_MEDIA = 'SEARCH_MEDIA';
export const RESET_CATEGORY_DETAIL = 'RESET_CATEGORY_DETAIL';
export const RESET_MEDIA_DETAIL = 'RESET_MEDIA_DETAIL';
export const LOGIN_FB = 'LOGIN_FB';
export const LOGIN_GOOGLE = 'LOGIN_GOOLE';
export const LOGOUT = 'LOGOUT';

export const GET_RELATIVE_MEDIA = 'GET_RELATIVE_MEDIA';
export const GET_RELATIVE_MEDIA_HOT = 'GET_RELATIVE_MEDIA_HOT';
export const GET_RELATIVE_MEDIA_FOLLOWED = 'GET_RELATIVE_MEDIA_FOLLOWED';
export const GET_RELATIVE_MEDIA_FAVORITED = 'GET_RELATIVE_MEDIA_FAVORITED';
export const GET_RELATIVE_MEDIA_NEW = 'GET_RELATIVE_MEDIA_NEW';
export const RESET_RELATIVE_MEDIA = 'RESET_RELATIVE_MEDIA';

export const COMMENT_ACTION = 'COMMENT_ACTION';
export const GET_LIST_COMMENT_ACTION = 'GET_LIST_COMMENT_ACTION';
export const RESET_LIST_COMMENT_ACTION = 'RESET_LIST_COMMENT_ACTION';

export const FACEBOOK = 'facebook';
export const GOOGLE = 'google';

export const RP1 = 'RP1';
export const RP2 = 'RP2';
export const RP3 = 'RP3';